# Generated by Django 6.1.1 on 2026-09-09 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_commande'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='adresse_livraison',
            field=models.TextField(default='Non spécifiée'),
        ),
        migrations.AddField(
            model_name='commande',
            name='date_mise_a_jour',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='commande',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente de validation'), ('approuve', 'Paiement Validé'), ('emballe', 'Commande Emballée'), ('expedie', 'En cours de Livraison'), ('livre', 'Livré avec Succès'), ('rejete', 'Commande Rejetée')], default='en_attente', max_length=20),
        ),
    ]
