# Generated by Django 6.1.1 on 2026-09-09 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_commande_adresse_livraison_commande_date_mise_a_jour_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='adresse_livraison',
            field=models.TextField(blank=True, default='Non spécifiée', null=True),
        ),
    ]
